server.port=8001
spring.main.allow-circular-references=true


#video files are stored in these paths



#video files are stored in these paths
storage.final-store-location=local
storage.local.original-store-path=/commonstore/original_uploads
storage.local.transcoded-store-path=/commonstore/transcoded
storage.local.nsfw-tests-path=/commonstore/nsfw_tests
storage.local.final-store-path=/commonstore/video
storage.local.live-record-base-path=/commonstore/live_record

#NSFW filter configuration

#nsfw.skip-check = y ->  nsfw check will be skipped
nsfw.skip-check=y
nsfw.skip-symbol=y
nsfw.fps=1/2
nsfw.minimum-safe-percent=50
nsfw.output-format=%04d.png
nsfw.nsfw-tests-path=/commonstore/nsfw_tests

server.error.whitelabel.enabled=false
server.tomcat.threads.max=200





#https fix try
server.tomcat.uri-encoding=UTF-8


#tailwind
spring.mvc.static-path-pattern=/**

#logging.level.ROOT=DEBUG



#********************************************************************************

#                                  RABBITMQ CONFIG

spring.rabbitmq.host=rabbit
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

rabbit.transcode.queue=transcode
rabbit.nsfw.queue=nsfw
rabbit.dash.queue=dash
rabbit.mp4.queue=mp4
rabbit.finalize.queue=finalize
rabbit.fail.queue=fail

rabbit.transcode.routing=transcode_rout
rabbit.nsfw.routing=nsfw_rout
rabbit.dash.routing=dash_rout
rabbit.mp4.routing=mp4_rout
rabbit.finalize.routing=finalize_rout
rabbit.fail.routing=fail_rout



rabbit.pipeline.exchange=video_pipeline
#************************************************************************************

# (optional/false/forced)
mp4.fallback=forced



spring.main.allow-bean-definition-overriding=true